/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author s1601396
 */
public class TexasHoldem extends javax.swing.JFrame {

    int Cards = 0;
    int Card = 1;
    int Gender = 1;

    /**
     * Creates new form TexasHoldem
     */
    public TexasHoldem() {
        initComponents();
        jButton2.setVisible(false);
        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P1C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P2C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P2C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P3C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P3C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P4C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P4C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P5C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P5C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P3B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P3B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P2B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P2B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P4B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P4B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P5B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        P5B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        CardStack = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        P5B2 = new javax.swing.JLabel();
        P5B1 = new javax.swing.JLabel();
        P5C2 = new javax.swing.JLabel();
        P5C1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        P4B2 = new javax.swing.JLabel();
        P4B1 = new javax.swing.JLabel();
        P4C2 = new javax.swing.JLabel();
        P4C1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        P2B2 = new javax.swing.JLabel();
        P2B1 = new javax.swing.JLabel();
        P2C2 = new javax.swing.JLabel();
        P2C1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        P1C2 = new javax.swing.JLabel();
        P1C1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        P3B2 = new javax.swing.JLabel();
        P3B1 = new javax.swing.JLabel();
        P3C2 = new javax.swing.JLabel();
        P3C1 = new javax.swing.JLabel();
        Card5 = new javax.swing.JLabel();
        Card4 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texas Holdem");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jToggleButton1.setText("Ready");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 110));

        CardStack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardStack.png"))); // NOI18N
        getContentPane().add(CardStack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 206, -1, -1));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P5B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel6.add(P5B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 1, -1, -1));

        P5B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel6.add(P5B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 1, -1, -1));

        P5C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_2.png"))); // NOI18N
        jPanel6.add(P5C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 1, -1, -1));

        P5C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_1.png"))); // NOI18N
        jPanel6.add(P5C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 1, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 90, 80));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P4B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel5.add(P4B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 1, -1, -1));

        P4B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel5.add(P4B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 1, -1, -1));

        P4C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_2.png"))); // NOI18N
        jPanel5.add(P4C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 1, -1, -1));

        P4C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_1.png"))); // NOI18N
        jPanel5.add(P4C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 1, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 80));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P2B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel2.add(P2B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 10, -1, -1));

        P2B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel2.add(P2B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, -1));

        P2C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_2.png"))); // NOI18N
        jPanel2.add(P2C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 10, -1, -1));

        P2C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_1.png"))); // NOI18N
        jPanel2.add(P2C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 90, 80));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_2.png"))); // NOI18N
        jPanel3.add(P1C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 10, -1, -1));

        P1C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_1.png"))); // NOI18N
        jPanel3.add(P1C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 90, 80));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P3B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel4.add(P3B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 10, -1, -1));

        P3B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png"))); // NOI18N
        jPanel4.add(P3B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, -1));

        P3C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_2.png"))); // NOI18N
        jPanel4.add(P3C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 10, -1, -1));

        P3C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/1_1.png"))); // NOI18N
        jPanel4.add(P3C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 90, 80));
        getContentPane().add(Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 206, -1, 70));
        getContentPane().add(Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 206, -1, 70));
        getContentPane().add(Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 206, -1, 70));
        getContentPane().add(Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 206, -1, 70));
        getContentPane().add(Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 206, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/CardTable.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/Background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        setSize(new java.awt.Dimension(811, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Cards++;
        if (Cards == 1) {
            for (int i = 1; i <= 5; i++) {

                while (true) {
                    Gender = CardShuffle.ShuffleGender();
                    Card = CardShuffle.ShuffleNum();
                    double luku = CardTest.PlayerCards(i, 1, Card, Gender);
                    if (i == 1 && luku == 0) {
                        P1C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 2 && luku == 0) {
                        P2C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 3 && luku == 0) {
                        P3C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 4 && luku == 0) {
                        P4C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 5 && luku == 0) {
                        P5C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    }

                }

                while (true) {
                    Gender = CardShuffle.ShuffleGender();
                    Card = CardShuffle.ShuffleNum();
                    double luku = CardTest.PlayerCards(i, 2, Card, Gender);
                    if (i == 1 && luku == 0) {
                        P1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 2 && luku == 0) {
                        P2C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 3 && luku == 0) {
                        P3C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 4 && luku == 0) {
                        P4C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    } else if (i == 5 && luku == 0) {
                        P5C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                        break;
                    }
                }
            }
            P3B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P3B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P2B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P2B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P4B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P4B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P5B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
            P5B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/PlayCardBack.png")));
        } else if (Cards == 2) {
            
            while (true) {
                Gender = CardShuffle.ShuffleGender();
                Card = CardShuffle.ShuffleNum();
                double luku = CardTest.Test(1, Card, Gender);
                if (luku == 0) {
                    Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                    break;
                }
            }

            while (true) {
                Gender = CardShuffle.ShuffleGender();
                Card = CardShuffle.ShuffleNum();
                double luku = CardTest.Test(2, Card, Gender);
                if (luku == 0) {
                    Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                    break;
                }
            }

            while (true) {
                Gender = CardShuffle.ShuffleGender();
                Card = CardShuffle.ShuffleNum();
                double luku = CardTest.Test(3, Card, Gender);
                if (luku == 0) {
                    Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                    break;
                }
            }

        } else if (Cards == 3) {
            while (true) {
                Gender = CardShuffle.ShuffleGender();
                Card = CardShuffle.ShuffleNum();
                double luku = CardTest.Test(4, Card, Gender);
                if (luku == 0) {
                    Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                    break;
                }
            }
        } else if (Cards == 4) {
            while (true) {
                Gender = CardShuffle.ShuffleGender();
                Card = CardShuffle.ShuffleNum();
                double luku = CardTest.Test(5, Card, Gender);
                if (luku == 0) {
                    Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
                    break;
                }
            }
            jToggleButton1.setVisible(true);
            jButton2.setVisible(false);
            Cards = 0;
            
            P3B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P3B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P2B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P2B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P4B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P4B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P5B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P5B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            jToggleButton1.setText("Clear");
            jToggleButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton2.doClick();
        } else {
            jToggleButton1.setText("Ready");
            Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P1C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P2C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P2C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P3C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P3C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P4C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P4C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P5C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P5C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TexasHoldem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Card4;
    private javax.swing.JLabel Card5;
    private javax.swing.JLabel CardStack;
    private javax.swing.JLabel P1C1;
    private javax.swing.JLabel P1C2;
    private javax.swing.JLabel P2B1;
    private javax.swing.JLabel P2B2;
    private javax.swing.JLabel P2C1;
    private javax.swing.JLabel P2C2;
    private javax.swing.JLabel P3B1;
    private javax.swing.JLabel P3B2;
    private javax.swing.JLabel P3C1;
    private javax.swing.JLabel P3C2;
    private javax.swing.JLabel P4B1;
    private javax.swing.JLabel P4B2;
    private javax.swing.JLabel P4C1;
    private javax.swing.JLabel P4C2;
    private javax.swing.JLabel P5B1;
    private javax.swing.JLabel P5B2;
    private javax.swing.JLabel P5C1;
    private javax.swing.JLabel P5C2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
