/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author s1601396
 */
public class TexasHoldem extends javax.swing.JFrame {

    int Cards = 0;
    int Card = 1;
    int Gender = 1;

    /**
     * Creates new form TexasHoldem
     */
    public TexasHoldem() {
        initComponents();
        jButton2.setVisible(false);
        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        P1C2 = new javax.swing.JLabel();
        P1C1 = new javax.swing.JLabel();
        Card5 = new javax.swing.JLabel();
        Card4 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texas Holdem");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        jToggleButton1.setText("Play");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 800, 110));
        getContentPane().add(P1C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));
        getContentPane().add(P1C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));
        getContentPane().add(Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 206, -1, 70));
        getContentPane().add(Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 206, -1, 70));
        getContentPane().add(Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 206, -1, 70));
        getContentPane().add(Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 206, -1, 70));
        getContentPane().add(Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 206, -1, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/CardTable.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/Background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        setSize(new java.awt.Dimension(811, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cards++;
        if (Cards == 1) {
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            P1C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            P1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));

        } else if (Cards == 2) {
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
            
        } else if (Cards == 3) {
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
            
        } else if (Cards == 4) {
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
            
        } else if (Cards == 5) {
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
            
        } else if (Cards == 6) {
            Gender = CardShuffle.ShuffleGender();
            Card = CardShuffle.ShuffleNum();
            Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PlayCards/" + Card + "_" + Gender + ".png")));
            
            jToggleButton1.setVisible(true);
            jButton2.setVisible(false);
            Cards = 0;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            jToggleButton1.setText("Clear");
            jToggleButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton2.doClick();
        } else {
            jToggleButton1.setText("Play");
            Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P1C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            P1C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TexasHoldem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TexasHoldem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Card4;
    private javax.swing.JLabel Card5;
    private javax.swing.JLabel P1C1;
    private javax.swing.JLabel P1C2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
